---
name: "Metadata Organiser"
guid: "68210EB1-7275-40F6-9568-DF276A9F9A3B"
version: "10.9.10.0"
targetAbi: "10.9.10.0"
framework: "net8.0"
overview: "Automatically handle assignment and reading of metadata to/from files"
description: >
  This plugin automatically handles assignment of metadata to files and modifying metadata read from files. 
category: "Metadata Organiser"
owner: "geo-martino"
artifacts:
- "Jellyfin.Plugin.MetadataOrganiser.dll"
changelog: >
  changelog
